#!/usr/bin/env bash
# Serial driver for the CBG finals: 3 operator ASNs x {mesh, traffic-weighted},
# plus as7018_us_test01 as a mesh-only public counterpart. Seven runs.
#
# Each config runs to completion before the next; a failure is logged and the
# batch continues. Per-config logs + a rollup live under logs/finals/.
#
# Usage:  tmux new-session -d -s cbg_finals "bash run_finals.sh"
#         bash run_finals.sh --dry-run     # preflight only, run nothing
#
# The weighted arms need a mesh ANNOTATED WITH REAL TRAFFIC VOLUME -- the plain
# meshes carry no weight column. Set those paths in the *-weighted.yaml configs
# (source_kwargs.mesh_csv_path). The preflight below refuses to start until they
# exist, rather than skipping them and leaving you with a half-finished batch.
#
# Each weighted arm is two steps: derive the traffic-weighted subset beside its
# mesh, then run against it (precomputed mode), so the same CSV feeds both the
# benchmark and the §8.1 dataset figures.
#
# Run ids are NEW (-mesh / -weighted suffixes). The published
# as0X-260728-260802 trees are never written to: their CSVs are reconstructions
# whose folds are pinned by a stored stratification, which re-materializing with
# (k=5, seed=42) would not reproduce.

set -uo pipefail            # no -e: keep going if one config fails
cd "$(dirname "$0")"
export PATH="$PWD/.venv/bin:$PATH"   # cli.sh calls `python`; resolve to the venv

DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

LOGDIR="logs/finals"
mkdir -p "$LOGDIR"
SUMMARY="$LOGDIR/_summary.log"
: > "$SUMMARY"

DERIVE_SMK="scripts/processing/source/derive_traffic_weighted_cbg_data.smk"

# Mesh arms: run directly.
MESH_CONFIGS=(
  as01-260728-260802-mesh
  as02-260728-260802-mesh
  as03-260728-260802-mesh
  as7018_us_test01-mesh
)

# Weighted arms: derive the subset first, then run.
WEIGHTED_CONFIGS=(
  as01-260728-260802-weighted
  as02-260728-260802-weighted
  as03-260728-260802-weighted
)

log() { echo "[$(date '+%F %T')] $*" | tee -a "$SUMMARY"; }

# Read a source_kwargs path out of a config (nested under `benchmark:`).
cfg_path() {  # $1=config stem  $2=key
  python - "$1" "$2" <<'PY'
import sys, yaml
cfg, key = sys.argv[1], sys.argv[2]
d = yaml.safe_load(open(f"configs/{cfg}.yaml"))["benchmark"]["source_kwargs"]
print(d.get(key, ""))
PY
}

# ---- preflight: every input must exist before anything runs -----------------
log "preflight: checking inputs for ${#MESH_CONFIGS[@]} mesh + ${#WEIGHTED_CONFIGS[@]} weighted runs"
MISSING=()
for c in "${MESH_CONFIGS[@]}"; do
  p=$(cfg_path "$c" csv_path)
  [[ -f "$p" ]] || MISSING+=("$c: csv_path $p")
done
for c in "${WEIGHTED_CONFIGS[@]}"; do
  p=$(cfg_path "$c" mesh_csv_path)
  # Only the weight-bearing mesh must pre-exist; the subset is derived below.
  [[ -f "$p" ]] || MISSING+=("$c: mesh_csv_path $p")
done

if (( ${#MISSING[@]} )); then
  log "ABORT: ${#MISSING[@]} required input(s) missing -- nothing was run:"
  for m in "${MISSING[@]}"; do log "         $m"; done
  log "       Weight-bearing meshes are not generated by this repo. Point the"
  log "       *-weighted.yaml configs at your traffic-annotated exports, or run"
  log "       only the mesh arms."
  exit 1
fi
log "preflight OK"

if (( DRY_RUN )); then
  log "--dry-run: preflight only, exiting before any run"
  exit 0
fi

# ---- weighted arms: derive the subset, then run -----------------------------
for c in "${WEIGHTED_CONFIGS[@]}"; do
  mesh=$(cfg_path "$c" mesh_csv_path)
  log "START $c (derive subset from $(basename "$mesh"))"
  if ! python -m snakemake -s "$DERIVE_SMK" --cores 1 \
         --config mesh="$mesh" >"$LOGDIR/$c.derive.log" 2>&1; then
    log "FAIL  $c (subset derivation; see $LOGDIR/$c.derive.log)"
    continue          # no subset -> the run would fail anyway
  fi
  if ./cli.sh --configfile "configs/$c.yaml" >"$LOGDIR/$c.log" 2>&1; then
    log "OK    $c"
  else
    log "FAIL  $c (see $LOGDIR/$c.log)"
  fi
done

# ---- mesh arms --------------------------------------------------------------
for c in "${MESH_CONFIGS[@]}"; do
  log "START $c"
  if ./cli.sh --configfile "configs/$c.yaml" >"$LOGDIR/$c.log" 2>&1; then
    log "OK    $c"
  else
    log "FAIL  $c (see $LOGDIR/$c.log)"
  fi
done

log "ALL DONE"
